services:
  - type: web
    name: medical-assistant
    env: python
    plan: free
    buildCommand: |
      apt-get update && \
      apt-get install -y python3-all-dev ffmpeg libasound2-dev libportaudio2 libportaudiocpp0 portaudio19-dev libsndfile1 libsndfile1-dev libespeak-dev && \
      pip install --upgrade pip && \
      pip install wheel && \
      pip install -r requirements.txt
    startCommand: streamlit run app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: POETRY_VERSION
        value: 1.7.1
    healthCheckPath: /_stcore/health
    autoDeploy: true 